# Generated by Django 6.1.1 on 2026-10-02 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('GROSSISTE', 'Grossiste'), ('DETAILLANT', 'Détail')], default='DETAILLANT', max_length=20)),
                ('nom_commercial', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.EmailField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
